name: Django Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo apt update
          sudo apt install docker-compose -y

      - name: Build and run containers
        run: |
          docker-compose up -d --build

      - name: Wait for services to be ready
        run: sleep 10

      - name: Run pytest tests
        run: |
          docker-compose exec -T web pytest

      - name: Tear down
        if: always()
        run: docker-compose down
